set_property IOSTANDARD LVCMOS33 [get_ports {ARDUINO_IO9[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARDUINO_IO8[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports iic_rtl_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_rtl_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod1_pin1_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod1_pin2_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod1_pin3_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod1_pin4_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod1_pin7_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod1_pin8_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod1_pin9_io]
set_property IOSTANDARD LVCMOS33 [get_ports Pmod1_pin10_io]
set_property IOSTANDARD LVCMOS33 [get_ports {ARDUINO_IO10[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_IO11]
set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_IO12]
set_property IOSTANDARD LVCMOS33 [get_ports ARDUINO_IO13]
set_property IOSTANDARD LVCMOS33 [get_ports {ARDUINO_IO7[0]}]
set_property PACKAGE_PIN L15 [get_ports Pmod1_pin1_io]
set_property PACKAGE_PIN M15 [get_ports Pmod1_pin2_io]
set_property PACKAGE_PIN L14 [get_ports Pmod1_pin3_io]
set_property PACKAGE_PIN M14 [get_ports Pmod1_pin4_io]
set_property PACKAGE_PIN K13 [get_ports Pmod1_pin7_io]
set_property PACKAGE_PIN L13 [get_ports Pmod1_pin8_io]
set_property PACKAGE_PIN N13 [get_ports Pmod1_pin9_io]
set_property PACKAGE_PIN N14 [get_ports Pmod1_pin10_io]
set_property PACKAGE_PIN M10 [get_ports {ARDUINO_IO10[0]}]
set_property PACKAGE_PIN M11 [get_ports ARDUINO_IO11]
set_property PACKAGE_PIN R11 [get_ports ARDUINO_IO12]
set_property PACKAGE_PIN P11 [get_ports ARDUINO_IO13]
set_property PACKAGE_PIN N8 [get_ports {ARDUINO_IO7[0]}]
set_property PACKAGE_PIN G15 [get_ports iic_rtl_scl_io]
set_property PACKAGE_PIN F15 [get_ports iic_rtl_sda_io]
set_property PACKAGE_PIN M9 [get_ports {ARDUINO_IO8[0]}]
set_property PACKAGE_PIN N9 [get_ports {ARDUINO_IO9[0]}]




set_property IOSTANDARD LVCMOS33 [get_ports pl_sw_1bit_tri_i]
